// GENERATED by scripts/buildContentManifest.mjs. Do not edit by hand.
// Run `npm run content:build` to regenerate it.

import type { QualityReport } from './types/QualityReport';

export const QUALITY_REPORT: QualityReport | null = null;
