// GENERATED by scripts/buildContentManifest.mjs. Do not edit by hand.
// Run `npm run content:build` to regenerate it.

export const BUNDLED_BANKS: Record<string, unknown> = {
  'frontend-security/easy': require('../../content/frontend-security/easy.json'),
};
