// GENERATED by scripts/buildContentManifest.mjs. Do not edit by hand.
// Run `npm run content:build` to regenerate it.

import type { Manifest } from './types/Manifest';

export const BUNDLED_MANIFEST = require('../../content/manifest.json') as Manifest;
