// Build step for the content bundle: hashes every question bank into
// content/manifest.json, validates banks and manifest with the app's own
// validators, and generates the TypeScript index that bundles them offline.
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { CONTENT_LIMITS } from '../constants/appConfig.ts';
import { validateManifest } from '../services/content/validateManifest.ts';
import { validateQuestionBank } from '../services/content/validateQuestionBank.ts';

const UTF8_BYTE_ORDER_MARK = [0xef, 0xbb, 0xbf];
const GENERATED_HEADER = `// GENERATED by scripts/buildContentManifest.mjs. Do not edit by hand.
// Run \`npm run content:build\` to regenerate it.
`;

function hasByteOrderMark(bytes) {
  return UTF8_BYTE_ORDER_MARK.every((byte, index) => bytes[index] === byte);
}

function listBankEntries(manifest) {
  return manifest.languages.flatMap((language) =>
    Object.entries(language.banks).map(([difficulty, bank]) => ({ language, difficulty, bank })),
  );
}

async function readBankBytes(contentDir, bankPath) {
  const bytes = await readFile(join(contentDir, bankPath));
  if (bytes.length > CONTENT_LIMITS.bankBytes) {
    throw new Error(`${bankPath} is over the ${CONTENT_LIMITS.bankBytes} byte limit`);
  }
  if (hasByteOrderMark(bytes)) throw new Error(`${bankPath} starts with a UTF-8 byte-order mark`);
  return bytes;
}

function assertValidBank(bankPath, bytes) {
  const result = validateQuestionBank(JSON.parse(bytes.toString('utf8')));
  if (!result.isValid) throw new Error(`${bankPath} is invalid: ${result.rule}`);
  if (result.droppedQuestionIds.length > 0) {
    throw new Error(`${bankPath} has invalid questions: ${result.droppedQuestionIds.join(', ')}`);
  }
}

async function hashBank(contentDir, bank) {
  const bytes = await readBankBytes(contentDir, bank.path);
  assertValidBank(bank.path, bytes);
  return createHash('sha256').update(bytes).digest('hex');
}

async function hashAllBanks(contentDir, manifest) {
  await Promise.all(
    listBankEntries(manifest).map(async ({ bank }) => {
      bank.hash = await hashBank(contentDir, bank);
    }),
  );
}

function assertValidManifest(manifest) {
  const result = validateManifest(manifest);
  if (!result.isValid) throw new Error(`manifest.json is invalid: ${result.rule}`);
}

function toRequirePath(generatedPath, contentDir, bankPath) {
  const relativePath = relative(dirname(generatedPath), join(contentDir, bankPath)).split(sep).join('/');
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function renderGeneratedSource(manifest, bankLines) {
  return `${GENERATED_HEADER}
export const BUNDLED_MANIFEST = ${JSON.stringify(manifest, null, 2)};

export const BUNDLED_BANKS: Record<string, unknown> = {
${bankLines.join('\n')}
};
`;
}

export async function buildContentManifest(contentDir, generatedPath) {
  const manifestPath = join(contentDir, 'manifest.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  await hashAllBanks(contentDir, manifest);
  assertValidManifest(manifest);
  const bankLines = listBankEntries(manifest).map(
    ({ language, difficulty, bank }) =>
      `  '${language.id}/${difficulty}': require('${toRequirePath(generatedPath, contentDir, bank.path)}'),`,
  );
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  if (Buffer.byteLength(manifestText, 'utf8') > CONTENT_LIMITS.manifestBytes) {
    throw new Error(`manifest.json is over the ${CONTENT_LIMITS.manifestBytes} byte limit`);
  }
  await writeFile(manifestPath, manifestText);
  await mkdir(dirname(generatedPath), { recursive: true });
  await writeFile(generatedPath, renderGeneratedSource(manifest, bankLines));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildContentManifest('content', 'services/content/bundledContent.generated.ts').catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
