// Build step for the content bundle: hashes every question bank into
// content/manifest.json, validates banks and manifest with the app's own
// validators, and generates the TypeScript modules that bundle them offline:
// one exporting the manifest and one exporting the bank require map.
//
// Paid banks never live in this public repo (B-60): they are in the private
// syntactical-content repo, passed in as `contentRoot`. Without it, paid entries
// keep the hash, topic counts, and version already in the manifest. Paid banks
// are never bundled, and the build fails on a paid bank file under content/ or a
// free bank file under the content root.
import {
  CONTENT_LIMITS,
  buildBankContext,
  collectMisconceptionIds,
  findMisconceptionsProblem,
  isSafeBankPath,
  validateManifest,
  validateQuestionBank,
} from '@syntactical/content-schema';
import { createHash } from 'node:crypto';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';

const UTF8_BYTE_ORDER_MARK = [0xef, 0xbb, 0xbf];
const GENERATED_HEADER = `// GENERATED by scripts/buildContentManifest.mjs. Do not edit by hand.
// Run \`npm run content:build\` to regenerate it.
`;

function hasByteOrderMark(bytes) {
  return UTF8_BYTE_ORDER_MARK.every((byte, index) => bytes[index] === byte);
}

function listBankEntries(manifest) {
  return manifest.languages.flatMap((language) =>
    Object.entries(language.banks).map(([difficulty, bank]) => ({ language, difficulty, bank })),
  );
}

async function readBankBytes(baseDir, bankPath) {
  if (!isSafeBankPath(bankPath)) throw new Error(`${bankPath} is not a safe bank path`);
  const bytes = await readFile(join(baseDir, bankPath));
  if (bytes.length > CONTENT_LIMITS.bankBytes) {
    throw new Error(`${bankPath} is over the ${CONTENT_LIMITS.bankBytes} byte limit`);
  }
  if (hasByteOrderMark(bytes)) throw new Error(`${bankPath} starts with a UTF-8 byte-order mark`);
  return bytes;
}

function buildLanguageContext(bankPath, language) {
  if (!Array.isArray(language.topics) || !Array.isArray(language.misconceptions)) {
    throw new Error(`manifest.json is invalid: ${language.id} has no topics or misconceptions for ${bankPath}`);
  }
  return buildBankContext(language);
}

function assertValidBank(bankPath, bytes, language) {
  const result = validateQuestionBank(JSON.parse(bytes.toString('utf8')), buildLanguageContext(bankPath, language));
  if (!result.isValid) throw new Error(`${bankPath} is invalid: ${result.rule}`);
  if (result.droppedQuestionIds.length > 0) {
    throw new Error(`${bankPath} has invalid questions: ${result.droppedQuestionIds.join(', ')}`);
  }
}

// Counts a bank's questions per topic; a question with no topic is not counted.
function countTopics(bytes) {
  const counts = {};
  for (const question of JSON.parse(bytes.toString('utf8')).questions) {
    if (typeof question?.topic === 'string') counts[question.topic] = (counts[question.topic] ?? 0) + 1;
  }
  return counts;
}

// A paid bank is read from the private content root; every other bank is read from the
// public content directory.
function pickBankDir(contentDir, contentRoot, bank) {
  return bank.access === 'paid' ? contentRoot : contentDir;
}

async function isFilePresent(path) {
  return (await stat(path).catch(() => null))?.isFile() ?? false;
}

// B-60: a paid bank file under content/ would ship on the static host, and a free bank file
// under the content root means the two trees were mixed up; either fails the build.
async function assertBanksInTheirTrees(contentDir, manifest, contentRoot) {
  for (const { bank, difficulty, language } of listBankEntries(manifest)) {
    const bankKey = `${language.id}/${difficulty}`;
    if (bank.access === 'paid' && (await isFilePresent(join(contentDir, bank.path)))) {
      throw new Error(`paid bank in public content: ${bankKey}`);
    }
    if (contentRoot && bank.access !== 'paid' && (await isFilePresent(join(contentRoot, bank.path)))) {
      throw new Error(`free bank in private content: ${bankKey}`);
    }
  }
}

// Recomputes the bank's hash and topic counts, and bumps its content version only when the
// hash changed, so a rebuild with no content change is a no-op. Without a content root a paid
// bank is not read and its manifest entry is kept as it is.
async function hashAllBanks(contentDir, manifest, contentRoot) {
  await Promise.all(
    listBankEntries(manifest).map(async ({ bank, language }) => {
      if (bank.access === 'paid' && !contentRoot) return;
      const bytes = await readBankBytes(pickBankDir(contentDir, contentRoot, bank), bank.path);
      assertValidBank(bank.path, bytes, language);
      const hash = createHash('sha256').update(bytes).digest('hex');
      if (hash !== bank.hash) bank.contentVersion += 1;
      bank.hash = hash;
      bank.topicCounts = countTopics(bytes);
    }),
  );
}

// Names an unsafe bank path before anything else, so the error points at the
// path itself and no file outside the content directory is ever read.
function assertSafeBankPaths(manifest) {
  for (const language of Array.isArray(manifest?.languages) ? manifest.languages : []) {
    for (const bank of Object.values(language?.banks ?? {})) {
      const bankPath = bank?.path;
      if (typeof bankPath === 'string' && !isSafeBankPath(bankPath)) {
        throw new Error(`${bankPath} is not a safe bank path`);
      }
    }
  }
}

// Validates the manifest's shape before any bank is read, so a malformed entry
// reports the manifest rule instead of failing deep in hashing. Hashes are
// recomputed afterwards, so stale or empty ones are replaced for this check.
function withPlaceholderHashes(manifest) {
  const copy = structuredClone(manifest);
  if (!Array.isArray(copy?.languages)) return copy;
  for (const language of copy.languages) {
    for (const bank of Object.values(language?.banks ?? {})) {
      if (bank && typeof bank === 'object') bank.hash = '0'.repeat(64);
    }
  }
  return copy;
}

function assertValidManifest(manifest) {
  const result = validateManifest(manifest);
  if (!result.isValid) throw new Error(`manifest.json is invalid: ${result.rule}`);
}

function toRequirePath(fromPath, targetPath) {
  const relativePath = relative(dirname(fromPath), targetPath).split(sep).join('/');
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function renderManifestSource(requirePath, isTyped) {
  const typeImport = isTyped ? "\nimport type { Manifest } from '@syntactical/content-schema';\n" : '';
  const typeCast = isTyped ? ' as Manifest' : '';
  return `${GENERATED_HEADER}${typeImport}
export const BUNDLED_MANIFEST = require('${requirePath}')${typeCast};
`;
}

function renderBanksSource(bankLines, hasHeader) {
  return `${hasHeader ? `${GENERATED_HEADER}\n` : ''}export const BUNDLED_BANKS: Record<string, unknown> = {
${bankLines.join('\n')}
};
`;
}

// Paid banks are never bundled: their files live outside this repo and reach owners through the API.
function listBankLines(contentDir, banksPath, manifest) {
  return listBankEntries(manifest)
    .filter(({ bank }) => bank.access !== 'paid')
    .map(({ language, difficulty, bank }) => ({
      key: `${language.id}/${difficulty}`,
      requirePath: toRequirePath(banksPath, join(contentDir, bank.path)),
    }))
    .sort((left, right) => (left.key < right.key ? -1 : 1))
    .map(({ key, requirePath }) => `  '${key}': require('${requirePath}'),`);
}

// `outputs` is either one module path (a single module exporting both the
// manifest and the banks) or { banksPath, manifestPath } (one export per file).
async function writeGeneratedModules(contentDir, outputs, manifest) {
  const isSplit = typeof outputs !== 'string';
  const banksPath = isSplit ? outputs.banksPath : outputs;
  const manifestPath = isSplit ? outputs.manifestPath : outputs;
  const manifestRequirePath = toRequirePath(manifestPath, join(contentDir, 'manifest.json'));
  const bankLines = listBankLines(contentDir, banksPath, manifest);
  await mkdir(dirname(manifestPath), { recursive: true });
  await mkdir(dirname(banksPath), { recursive: true });
  if (!isSplit) {
    const manifestSource = renderManifestSource(manifestRequirePath, false);
    await writeFile(outputs, `${manifestSource}\n${renderBanksSource(bankLines, false)}`);
    return;
  }
  await writeFile(manifestPath, renderManifestSource(manifestRequirePath, true));
  await writeFile(banksPath, renderBanksSource(bankLines, true));
}

async function readApprovedTaxonomy(taxonomyPath) {
  try {
    return JSON.parse(await readFile(taxonomyPath, 'utf8'));
  } catch (err) {
    // No approved file yet: the language keeps the misconceptions its manifest entry lists.
    if (err?.code === 'ENOENT') return undefined;
    throw err;
  }
}

// Keeps linked entries from each language's owner-approved `<language>.json`, retaining
// previously published ids when private banks are unavailable. The
// `<language>.draft.json` the pipeline writes is never read. Language ids are already
// validated (they are joined into the path), and a malformed approved file fails the build.
async function applyApprovedTaxonomies(taxonomyDir, manifest, contentDir, contentRoot) {
  for (const language of manifest.languages) {
    const approvedName = `${language.id}.json`;
    const misconceptions = await readApprovedTaxonomy(join(taxonomyDir, approvedName));
    if (misconceptions === undefined) continue;
    const problem = findMisconceptionsProblem(misconceptions, language.id);
    if (problem !== null) throw new Error(`taxonomy ${approvedName} is invalid: ${problem}`);
    const linkedIds = new Set(contentRoot ? [] : language.misconceptions.map(({ id }) => id));
    for (const bank of Object.values(language.banks)) {
      if (bank.access === 'paid' && !contentRoot) continue;
      const bytes = await readBankBytes(pickBankDir(contentDir, contentRoot, bank), bank.path);
      for (const question of JSON.parse(bytes.toString('utf8')).questions) {
        for (const id of collectMisconceptionIds(question)) linkedIds.add(id);
      }
    }
    language.misconceptions = misconceptions.filter(({ id }) => linkedIds.has(id));
  }
}

// `taxonomyDir` is optional: the folder of approved `<language>.json` misconception lists.
// `contentRoot` is optional: the private content repo that holds paid banks.
export async function buildContentManifest(contentDir, outputs, taxonomyDir, contentRoot) {
  const manifestPath = join(contentDir, 'manifest.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  assertSafeBankPaths(manifest);
  assertValidManifest(withPlaceholderHashes(manifest));
  if (taxonomyDir) await applyApprovedTaxonomies(taxonomyDir, manifest, contentDir, contentRoot);
  await assertBanksInTheirTrees(contentDir, manifest, contentRoot);
  await hashAllBanks(contentDir, manifest, contentRoot);
  assertValidManifest(manifest);
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  if (Buffer.byteLength(manifestText, 'utf8') > CONTENT_LIMITS.manifestBytes) {
    throw new Error(`manifest.json is over the ${CONTENT_LIMITS.manifestBytes} byte limit`);
  }
  await writeFile(manifestPath, manifestText);
  await writeGeneratedModules(contentDir, outputs, manifest);
}

// The repository's own build: its content, generated modules, and taxonomy
// paths, resolved against `repoDir` so it runs from any working directory. The pipeline's
// `publish` calls it with the private content root.
export function buildRepoContent(repoDir, contentRoot) {
  return buildContentManifest(
    join(repoDir, 'content'),
    {
      banksPath: join(repoDir, 'services/content/bundledBanks.generated.ts'),
      manifestPath: join(repoDir, 'services/content/bundledManifest.generated.ts'),
    },
    join(repoDir, 'pipeline/taxonomy'),
    contentRoot,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildRepoContent('.').catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
